 steps:
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '-r', 'requirements.txt']
    - name: 'python'
      entrypoint: 'python'
      args: ['app.py']
